name: Update Changelog

on:
  # push:
  #   branches:
  #     - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Skip if commit should not trigger changelog
        run: |
          git fetch origin main
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -q '\[skip changelog\]'; then
            echo "Skipping changelog update due to marker."
            exit 0
          fi

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore(CHANGELOG): update [skip changelog]" || echo "No changes to commit"
          git push
